---
name: Check Hugging Face Secret

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-hf-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check for HUGGING_FACE_HUB_TOKEN
        shell: bash
        run: |
          if [ -z "${{ secrets.HUGGING_FACE_HUB_TOKEN }}" ]; then
            echo "::warning ::HUGGING_FACE_HUB_TOKEN is not set."
          else
            echo "HUGGING_FACE_HUB_TOKEN is set."
          fi
